name: Deploy Docker Image to EC2

on:
  push:
    branches:
      - master  # Replace with your target branch
  pull_request: # Trigger on pull requests (optional)
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Replace with your AWS region

      # Step 3: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 277707115562.dkr.ecr.ap-south-1.amazonaws.com

      # Step 4: Build and tag the Docker image
      - name: Build and tag Docker image
        run: |
          docker build -t vehicles:latest .
          docker tag vehicles:latest 277707115562.dkr.ecr.ap-south-1.amazonaws.com/detection-repo:latest

      # Step 5: Push the Docker image to ECR
      - name: Push Docker image to Amazon ECR
        run: |
          docker push 277707115562.dkr.ecr.ap-south-1.amazonaws.com/detection-repo:latest

      # Step 6: Save EC2 private key to a file
      - name: Save EC2 private key to file
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private-key.pem
          chmod 600 private-key.pem

      # Step 7: Deploy the Docker image to EC2 
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private-key.pem ubuntu@43.205.114.77 << 'EOF'
          sudo apt update
          sudo apt install -y awscli
          aws ecr get-login-password --region ap-south-1 | sudo docker login --username AWS --password-stdin 277707115562.dkr.ecr.ap-south-1.amazonaws.com
          sudo docker pull 277707115562.dkr.ecr.ap-south-1.amazonaws.com/detection-repo:latest
          sudo docker stop $(sudo docker ps -q) || true
          sudo docker rm $(sudo docker ps -aq) || true
          sudo docker run -d -p 8080:8080 277707115562.dkr.ecr.ap-south-1.amazonaws.com/detection-repo:latest
      EOF



      # Step 8: Clean up private key
      - name: Clean up
        run: |
          rm -f private-key.pem
